theme: jekyll-theme-architect
title: Sauli Sarkar
description: Performance Marketer and Growth Hacker. Helping businesses grow by leveraging data-driven marketing strategies and performance optimization techniques.
author: Sauli Sarkar
url: https://saulisarkar.github.io
baseurl: ""
lang: en-US
show_downloads: false
google_analytics: G-0RKBSLBXP0
plugins:
  - jekyll-seo-tag
